apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: react-boilerplate-test
  description: |
    A service for testing Backstage functionality with React. Configured for
    GitHub Actions.
  annotations:
    github.com/project-slug: CloudOps | PlatformOps
spec:
  type: service
  owner: Parul
  lifecycle: production
