export const GET_FORM_REQUEST = "GET_FORM_REQUEST";
export const GET_FORM_SUCCESS = "GET_FORM_SUCCESS";
export const GET_FORM_FAILURE = "GET_FORM_FAILURE";

export const GET_FORM_REQUEST_FOR_EDIT = "GET_FORM_REQUEST_FOR_EDIT";
export const GET_FORM_SUCCESS_FOR_EDIT = "GET_FORM_SUCCESS_FOR_EDIT";
export const GET_FORM_FAILURE_FOR_EDIT = "GET_FORM_FAILURE_FOR_EDIT";

export const DELETE_FORM_REQUEST = "DELETE_FORM_REQUEST";
export const DELETE_FORM_SUCCESS = "DELETE_FORM_SUCCESS";
export const DELETE_FORM_ERROR = "DELETE_FORM_ERROR";

export const SHOW_LOADER = "sHOW_LOADER"
export const HIDE_LOADER = "HIDE_LOADER"
