export const HANDLE_DRAWER_TOGGLE_CHANGE = "HANDLE_DRAWER_TOGGLE_CHANGE";

export const GET_FORM_REQUEST = "GET_FORM_REQUEST";
export const GET_FORM_SUCCESS = "GET_FORM_SUCCESS";
export const GET_FORM_FAILURE = "GET_FORM_FAILURE";
